#!/usr/bin/env bash

if [ -z "$NVIM_LISTEN_ADDRESS" ]
then # NeoVim is _not_ already open in this terminal
  nvim $@
elif [ -z "$*" ]
then # NeoVim is already open -- no arguments were passed
  nvr +new
else # NeoVim is already open -- forward passed arguments
  nvr -cc split --remote-wait +'set bufhidden=wipe' $@
fi
